# This file was generated by the {rix} R package v0.17.2 on 2026-02-02
# with following call:
# >rix::rix(date = "2026-01-05",
#  > r_pkgs = NULL,
#  > system_pkgs = NULL,
#  > tex_pkgs = NULL,
#  > py_conf = list(py_version = "3.12",
#  > py_pkgs = c("numpy",
#  > "pandas",
#  > "matplotlib",
#  > "seaborn",
#  > "scikit-learn",
#  > "statsmodels",
#  > "openpyxl",
#  > "pytest",
#  > "jinja2")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-05.tar.gz") {};
   
  pyconf = builtins.attrValues {
    inherit (pkgs.python312Packages) 
      pip
      ipykernel
      jinja2
      matplotlib
      numpy
      openpyxl
      pandas
      pytest
      scikit-learn
      seaborn
      statsmodels;
  };
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      python312
      R;
  };
  
  shell = pkgs.mkShell {
    #LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux"
    then "${pkgs.glibcLocales}/lib/locale/locale-archive"
    else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    RETICULATE_PYTHON = "${pkgs.python312}/bin/python";

    #buildInputs = [ tex pyconf system_packages ];
    buildInputs = pyconf ++ system_packages;
    
    # 3. shellHook
    shellHook = ''
      export PYTHONUNBUFFERED=1
      echo "Nix shell ready."
    '';
    
  }; 
in
  {
    inherit pkgs shell;
  }
