from __future__ import annotations
from pathlib import Path
import json
import pandas as pd
from jinja2 import Template

HTML_TEMPLATE = r"""
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Forecasting Report (HW3)</title>
  <style>
    :root { --fg:#111; --muted:#555; --bg:#fff; --card:#f7f7f8; --border:#ddd; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
           margin: 40px; line-height: 1.55; color: var(--fg); background: var(--bg); }
    h1 { margin: 0 0 6px 0; font-size: 28px; }
    .meta { color: var(--muted); margin: 0 0 18px 0; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin: 16px 0; }
    .card { background: var(--card); border: 1px solid var(--border); border-radius: 10px; padding: 12px 14px; }
    .card h3 { margin: 0 0 6px 0; font-size: 15px; }
    code { background: #f0f2f4; padding: 2px 4px; border-radius: 4px; }
    table { border-collapse: collapse; margin-top: 10px; width: 520px; max-width: 100%; }
    th, td { border: 1px solid var(--border); padding: 8px 10px; }
    th { background: #f2f2f2; text-align: left; }
    .figure { margin-top: 18px; }
    .figure img { max-width: 100%; border: 1px solid var(--border); border-radius: 8px; }
    ul { margin: 8px 0 0 18px; }
    .small { color: var(--muted); font-size: 12px; margin-top: 6px; }
    hr { border: none; border-top: 1px solid var(--border); margin: 22px 0; }
  </style>
</head>
<body>

  <h1>RAP – Import Forecasting</h1>
  <p class="meta">
    Reproducible Analytical Pipeline output — generated automatically from this repository.
  </p>

  <div class="grid">
    <div class="card">
      <h3>Data & split</h3>
      <ul>
        <li>Target: <code>{{ target_col }}</code></li>
        <li>Predictor: <code>{{ x_col }}</code></li>
        <li>Analysis end: <code>{{ analysis_end }}</code></li>
        <li>Train size: <code>{{ n_train }}</code> (cutoff: <code>{{ cutoff_date }}</code>)</li>
        <li>Test period: <code>{{ test_start }}</code> → <code>{{ test_end }}</code></li>
        <li>Lags: <code>{{ lags }}</code></li>
      </ul>
    </div>

    <div class="card">
      <h3>Model selection</h3>
      <ul>
        <li>NN best params: <code>{{ nn_best_params }}</code></li>
        <li>ARIMA best order (BIC): <code>{{ arima_best_order }}</code></li>
        <li>VAR selected lag (BIC): <code>{{ var_selected_lag }}</code></li>
      </ul>
      <p class="small">NN uses recursive 1-step forecasts on differenced target and reconstructs levels.</p>
    </div>
  </div>

  <h2>RMSE comparison</h2>
  {{ rmse_table | safe }}

  <div class="figure">
    <h2>Forecast comparison plot</h2>
    <img src="{{ plot_filename }}" alt="Forecast comparison plot">
    <p class="small">Plot generated by the pipeline (saved under <code>outputs/</code>).</p>
  </div>

  <hr>

  <h2>Method summary (short)</h2>
  <h3>Neural Network</h3>
  <ul>
    <li>Transform: first difference on target (dy), predictor kept in levels.</li>
    <li>Features: 4 lags of dy and 4 lags of x.</li>
    <li>Hyperparameters: grid search with time-series cross-validation on training set.</li>
    <li>Forecasting: recursive 1-step ahead with re-estimation each step (no peeking).</li>
  </ul>

  <h3>Benchmarks</h3>
  <ul>
    <li>ARIMA: ARIMA(p,1,q) selected by BIC over a small grid; recursive 1-step forecasts.</li>
    <li>VAR: estimated on differenced (target, predictor); lag selected by BIC; recursive 1-step forecasts.</li>
  </ul>

  <p class="small">
    Generated at: <code>{{ generated_at }}</code>
  </p>

</body>
</html>
"""

def write_html_report(
    out_html: Path,
    rmse_df: pd.DataFrame,
    plot_filename: str,
    meta: dict
) -> None:
    rmse_table = rmse_df.to_html(index=False, float_format=lambda x: f"{x:.4f}")
    html = Template(HTML_TEMPLATE).render(
        rmse_table=rmse_table,
        plot_filename=plot_filename,
        **meta
    )
    out_html.write_text(html, encoding="utf-8")

def try_write_pdf_from_html(html_path: Path, pdf_path: Path) -> bool:
    try:
        from weasyprint import HTML
        HTML(filename=str(html_path)).write_pdf(str(pdf_path))
        return True
    except Exception:
        return False

def build_report_from_outputs(outputs_dir: Path) -> tuple[Path, Path | None]:
    """
    Convenience: read outputs (metadata.json, rmse.csv, plot) and generate report.html (+ report.pdf if possible)
    """
    meta_path = outputs_dir / "metadata.json"
    rmse_path = outputs_dir / "rmse.csv"
    plot_path = outputs_dir / "forecast_comparison.png"

    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    rmse_df = pd.read_csv(rmse_path)

    # flatten some fields for template
    tpl_meta = {
        "target_col": meta.get("outputs_meta", {}).get("target_col", meta.get("target_col", "import_clv_qna_sa")),
        "x_col": meta.get("outputs_meta", {}).get("x_col", meta.get("x_col", "import_s_clv_qna_sa")),
        "analysis_end": meta.get("analysis_end", meta.get("outputs_meta", {}).get("analysis_end", "")),
        "lags": meta.get("lags", meta.get("outputs_meta", {}).get("lags", "")),
        "n_train": meta.get("n_train", ""),
        "cutoff_date": meta.get("cutoff_date", ""),
        "test_start": meta.get("test_start", ""),
        "test_end": meta.get("test_end", ""),
        "nn_best_params": json.dumps(meta.get("nn_best_params", {})),
        "arima_best_order": meta.get("arima_best_order", ""),
        "var_selected_lag": meta.get("var_selected_lag", ""),
        "generated_at": pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"),
    }

    out_html = outputs_dir / "report.html"
    write_html_report(out_html, rmse_df, plot_path.name, tpl_meta)

    out_pdf = outputs_dir / "report.pdf"
    pdf_ok = try_write_pdf_from_html(out_html, out_pdf)
    return out_html, (out_pdf if pdf_ok else None)
